title = "Janine und Markus heiraten"
copyright = "{year}"

theme = "hugo-story"

relativeURLs = "true"
canonifyURLs = "true"

baseURL = "/"
publishDir = "public"

disableKinds = ["taxonomy", "section"]

[Params]
description = "Ein Leben lang ..."
logo = "images/banner.jpg"
favicon = true

[Params.social]
github = "https://github.com/Tiliavir/wedding"
email = "janine-und-markus-heiraten@outlook.de"

[markup.goldmark.renderer]
unsafe = true
